//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public int id { get; set; }
        public int room_id { get; set; }
        public string type { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> completed_at { get; set; }
    
        public virtual room room { get; set; }
    }
}
